# Try merging a pull request when it is approved.
name: merge pull-request
on:
    pull_request_review:
        types:
            - submitted

permissions:
    contents: read
    pull-requests: write

jobs:
    automerge:
        if: github.event.review.state == 'approved' || !github.event.review
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: merge pull request
              uses: sudo-bot/action-pull-request-merge@53b588daa0c2e217534166cda8e68e9d6faaa685 # v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ github.event.pull_request.number }}
                  merge-method: squash
